name: Launch App

on:
  workflow_dispatch:
    inputs:
      envName:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
    secrets:
      ssh_key:
        required: true  

jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      ip_address: 0.0.0.0
      envName: ${{ github.event.inputs.envName }}