name: Deploy Dev US

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: environment
        required: true

jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      ip_address: 'dev.example.com'
      envName: dev